# Generated by Django 4.2.6 on 2023-11-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_objectgroup_options_alter_upd_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='inn',
            field=models.CharField(max_length=30, unique=True, verbose_name='ИНН'),
        ),
    ]
